name: Cypress Tests

on:
  push:
    branches:
      - advanced

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start BackEnd Server
        run: |
          cd server
          # Use legacy-peer-deps to avoid the ERESOLVE error
          npm install --legacy-peer-deps
          npm start &
          # Wait for the API to be ready
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Waiting for server to start..."
            sleep 2
          done
          echo "Server is running successfully."

      - name: Start Web App FrontEnd
          run: |
            cd web
            npm install --legacy-peer-deps
            # CI=false prevents warnings from being treated as crash-errors
            CI=false BROWSER=none npm start &

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # Use the pre-installed node_modules and ignore peer conflicts
          install-command: npm install --legacy-peer-deps
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/login-clinica.cy.js
            cypress/e2e/dashboard.cy.js
          # Wait for both ports to be active before starting tests
          wait-on: 'http://localhost:3000, http://localhost:8080'
          wait-on-timeout: 120